format = """$status$hostname[ÓÇ∂](#e0e0e0)[$custom](bg:#e0e0e0 black)[ÓÇ¥](#e0e0e0)$cmd_duration
‚ùØ 
"""
right_format = """$character$git_branch$git_status"""

add_newline = false

palette = 'foo'

[palettes.foo]
grey="#808080"
green="#047e84"
blue="#0055aa"
red="#DD352E"
white="#e0e0e0"

# Prompt Symbols
[character]
success_symbol = '[‚ûú](bold green)'
error_symbol = '[‚úó](bold red) '

# Git Status
[git_status]
style="bg:#e0e0e0 black"
deleted="‚úò ${count} "
modified="!${count} "
staged="+${count} "
ahead="‚á°${count}"
untracked="?${count}"
format = "[$all_status$ahead_behind ]($style)"
up_to_date = '‚úì'

# Git Branch
[git_branch]
style="bg:#7F7F7F black"
format="[ $branch ]($style)"

# Command Status
[status]
symbol = '[‚úó](bg:#DD352E #000000 bold)'
success_symbol = ''
sigint_symbol=''
format = '$symbol'
map_symbol = true
disabled = false

# Time Display
[time]
disabled = false
time_format = "%H:%M"
format = "üïô[$time]($style) "

# Command Duration
[cmd_duration]
style = 'bg:#0055aa bold'
format="[$duration ]($style)"

# Custom Directory Path
[custom.dir]
command = 'Dirpath' 
when = true
format = '$output'

# Hostname
[hostname]
format = " $hostname "
## version: 1.0.0
#
#add_newline = true
#continuation_prompt = "[‚ñ∏‚ñπ ](dimmed white)"
#
#format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
#$hostname\
#$localip\
#$shlvl\
#$shell\
#$env_var\
#$jobs\
#$sudo\
#$username\
#$character"""
#
#right_format = """
#$singularity\
#$kubernetes\
#$directory\
#$vcsh\
#$fossil_branch\
#$git_branch\
#$git_commit\
#$git_state\
#$git_status\
#$hg_branch\
#$pijul_channel\
#$docker_context\
#$package\
#$c\
#$cmake\
#$cobol\
#$daml\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$fennel\
#$golang\
#$guix_shell\
#$haskell\
#$haxe\
#$helm\
#$java\
#$julia\
#$kotlin\
#$gradle\
#$lua\
#$nim\
#$nodejs\
#$ocaml\
#$opa\
#$perl\
#$php\
#$pulumi\
#$purescript\
#$python\
#$raku\
#$rlang\
#$red\
#$ruby\
#$rust\
#$scala\
#$solidity\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$buf\
#$conda\
#$meson\
#$spack\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$azure\
#$crystal\
#$custom\
#$status\
#$os\
#$battery\
#$time"""
#
#[fill]
#symbol = ' '
#
#[character]
#format = "$symbol "
#success_symbol = "[‚óé](bold italic bright-yellow)"
#error_symbol = "[‚óã](italic purple)"
#vimcmd_symbol = "[‚ñ†](italic dimmed green)"
## not supported in zsh
#vimcmd_replace_one_symbol = "‚óå"
#vimcmd_replace_symbol = "‚ñ°"
#vimcmd_visual_symbol = "‚ñº"
#
#[env_var.VIMSHELL]
#format = "[$env_value]($style)"
#style = 'green italic'
#
#[sudo]
#format = "[$symbol]($style)"
#style = "bold italic bright-purple"
#symbol = "‚ãà‚îà"
#disabled = false
#
#[username]
#style_user = "bright-yellow bold italic"
#style_root = "purple bold italic"
#format = "[‚≠ò $user]($style) "
#disabled = false
#show_always = false
#
#[directory]
#home_symbol = "‚åÇ"
#truncation_length = 2
#truncation_symbol = "‚ñ° "
#read_only = " ‚óà"
#use_os_path_sep = true
#style = "italic blue"
#format = '[$path]($style)[$read_only]($read_only_style)'
#repo_root_style = 'bold blue'
#repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [‚ñ≥](bold bright-blue)'
#
#[cmd_duration]
#format = "[‚óÑ $duration ](italic white)"
#
#[jobs]
#format = "[$symbol$number]($style) "
#style = "white"
#symbol = "[‚ñ∂](blue italic)"
#
#[localip]
#ssh_only = true
#format = " ‚óØ[$localipv4](bold magenta)"
#disabled = false
#
#[time]
#disabled = false
#format = "[ $time]($style)"
#time_format = "%R"
#utc_time_offset = "local"
#style = "italic dimmed white"
#
#[battery]
#format = "[ $percentage $symbol]($style)"
#full_symbol = "‚ñà"
#charging_symbol = "[‚Üë](italic bold green)"
#discharging_symbol = "‚Üì"
#unknown_symbol = "‚ñë"
#empty_symbol = "‚ñÉ"
#
#[[battery.display]]
#threshold = 20
#style = "italic bold red"
#
#[[battery.display]]
#threshold = 60
#style = "italic dimmed bright-purple"
#
#[[battery.display]]
#threshold = 70
#style = "italic dimmed yellow"
#
#[git_branch]
#format = " [$branch(:$remote_branch)]($style)"
#symbol = "[‚ñ≥](bold italic bright-blue)"
#style = "italic bright-blue"
#truncation_symbol = "‚ãØ"
#truncation_length = 11
#ignore_branches = ["main", "master"]
#only_attached = true
#
#[git_metrics]
#format = '([‚ñ¥$added]($added_style))([‚ñø$deleted]($deleted_style))'
#added_style = 'italic dimmed green'
#deleted_style = 'italic dimmed red'
#ignore_submodules = true
#disabled = false
#
#[git_status]
#style = "bold italic bright-blue"
#format = "([‚é™$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed‚é•]($style))"
#conflicted = "[‚ó™‚ó¶](italic bright-magenta)"
#ahead = "[‚ñ¥‚îÇ[${count}](bold white)‚îÇ](italic green)"
#behind = "[‚ñø‚îÇ[${count}](bold white)‚îÇ](italic red)"
#diverged = "[‚óá ‚ñ¥‚î§[${ahead_count}](regular white)‚îÇ‚ñø‚î§[${behind_count}](regular white)‚îÇ](italic bright-magenta)"
#untracked = "[‚óå‚ó¶](italic bright-yellow)"
#stashed = "[‚óÉ‚óà](italic white)"
#modified = "[‚óè‚ó¶](italic yellow)"
#staged = "[‚ñ™‚î§[$count](bold white)‚îÇ](italic bright-cyan)"
#renamed = "[‚óé‚ó¶](italic bright-blue)"
#deleted = "[‚úï](italic red)"
#
#[deno]
#format = " [deno](italic) [‚à´ $version](green bold)"
#version_format = "${raw}"
#
#[lua]
#format = " [lua](italic) [${symbol}${version}]($style)"
#version_format = "${raw}"
#symbol = "‚®Ä "
#style = "bold bright-yellow"
#
#[nodejs]
#format = " [node](italic) [‚ó´ ($version)](bold bright-green)"
#version_format = "${raw}"
#detect_files = ["package-lock.json", "yarn.lock"]
#detect_folders = ["node_modules"]
#detect_extensions = []
#
#[python]
#format = " [py](italic) [${symbol}${version}]($style)"
#symbol = "[‚åâ](bold bright-blue)‚åä "
#version_format = "${raw}"
#style = "bold bright-yellow"
#
#[ruby]
#format = " [rb](italic) [${symbol}${version}]($style)"
#symbol = "‚óÜ "
#version_format = "${raw}"
#style = "bold red"
#
#[rust]
#format = " [rs](italic) [$symbol$version]($style)"
#symbol = "‚äÉ "
#version_format = "${raw}"
#style = "bold red"
#
#[package]
#format = " [pkg](italic dimmed) [$symbol$version]($style)"
#version_format = "${raw}"
#symbol = "‚ó® "
#style = "dimmed yellow italic bold"
#
#[swift]
#format = " [sw](italic) [${symbol}${version}]($style)"
#symbol = "‚óÅ "
#style = "bold bright-red"
#version_format = "${raw}"
#
#[aws]
#disabled = true
#format = " [aws](italic) [$symbol $profile $region]($style)"
#style = "bold blue"
#symbol = "‚ñ≤ "
#
#[buf]
#symbol = "‚ñ† "
#format = " [buf](italic) [$symbol $version $buf_version]($style)"
#
#[c]
#symbol = "‚ÑÇ "
#format = " [$symbol($version(-$name))]($style)"
#
#[conda]
#symbol = "‚óØ "
#format = " conda [$symbol$environment]($style)"
#
#[dart]
#symbol = "‚óÅ‚óÖ "
#format = " dart [$symbol($version )]($style)"
#
#[docker_context]
#symbol = "‚óß "
#format = " docker [$symbol$context]($style)"
#
#[elixir]
#symbol = "‚ñ≥ "
#format = " exs [$symbol $version OTP $otp_version ]($style)"
#
#[elm]
#symbol = "‚ó© "
#format = " elm [$symbol($version )]($style)"
#
#[golang]
#symbol = "‚à© "
#format = " go [$symbol($version )]($style)"
#
#[haskell]
#symbol = "‚ùØŒª "
#format = " hs [$symbol($version )]($style)"
#
#[java]
#symbol = "‚à™ "
#format = " java [${symbol}(${version} )]($style)"
#
#[julia]
#symbol = "‚óé "
#format = " jl [$symbol($version )]($style)"
#
#[memory_usage]
#symbol = "‚ñ™‚ñ´‚ñ™ "
#format = " mem [${ram}( ${swap})]($style)"
#
#[nim]
#symbol = "‚ñ¥‚ñ≤‚ñ¥ "
#format = " nim [$symbol($version )]($style)"
#
#[nix_shell]
#style = 'bold italic dimmed blue'
#symbol = '‚ú∂'
#format = '[$symbol nix‚é™$state‚é™]($style) [$name](italic dimmed white)'
#impure_msg = '[‚åΩ](bold dimmed red)'
#pure_msg = '[‚åæ](bold dimmed green)'
#unknown_msg = '[‚óå](bold dimmed ellow)'
#
#[spack]
#symbol = "‚óá "
#format = " spack [$symbol$environment]($style)"
